### ISSUE TITLE
Correct all broken links listed in this issue

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1172] opened 2020-05-25 18:53 UTC
### Summary

* Upgrading Jupyterbook led to many broken links, which needs fixing

### What needs to be done?

- [ ] Correct broken links that will be soon listed below
- Please mark the links that are fixed

### Who can help?

* This issue is being created for the new contributors, please correct maximum 3-5 broken link so that others can also contribute to fixing these

### For the maintainers

- [ ] We have disabling the html proofer until all links are corrected (see #1171) - once all the links are fixed, please activate them again on the CI workflow
---

### Updates

* I will add this on 26 May 2020

**Comment by EstherPlomp** [comment] 2023-01-16 19:38
@da5nsy I think this issue is outdated with the new workflow to check links? Can we close this?

**Comment by da5nsy** [comment] 2023-01-24 22:45
Hmm, yes and no. 
It is outdated and should be closed 👍 
Looking into this has alerted me to the fact that the link checker does not seem to be working as intended though 👎  
(I'll make a new issue regarding that though)

**Closed by da5nsy** 2023-01-24 22:45 UTC
