### ISSUE TITLE
Make poster for T, P & S scoping workshop | Deadline 19 March

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#259] opened 2019-03-02 19:23 UTC
### Summary

At the Tools, Practices and Systems (TPS) scoping workshop, all the current projects are expected to present a poster on the project and what they've done so far.

***deadline: 19 March 2019***

### What needs to be done?

- [ ] Figure out content. We don't have a traditional "introduction, methods, results, conclusion" kinda project, so any suggestions on what should be covered on the poster would be great
- [ ] Make the poster - includes figures, text and layout.
  * We have a Turing template - I'm not sure if it can be public but I'll ask.
  * I've sent a message to Amber asking whether it needs to be portrait or landscape.

### Who can help?

* I'm thinking @pherterich might have some time to help with thinking about what should be covered.
* All members of the team to put their suggestions in please 🙏 

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by r-j-arnold** [comment] 2019-03-04 09:09
It should probably contain info on chapters planned/desired from the [book skeleton](https://github.com/alan-turing-institute/the-turing-way/blob/master/book_skeleton.md). Depending on time maybe you could arrange the chapters in a flow chart showing which ones are unlocked by preprequesites.

**Comment by pherterich** [comment] 2019-03-04 10:00
I could see a three column approach working with the handbook, BinderHub and community/workshops. If people like numbers, I'm quite sure we can get something nice out of the insights tab on GitHub + newsletter and workshop attendee numbers etc.

I can make a start on it tomorrow. I haven't created many posters in my life, so better suggestions than doing it in powerpoint are very welcome!

**Comment by LouiseABowler** [comment] 2019-03-04 10:22
Merging @r-j-arnold and @pherterich's ideas would give us a good layout - it'll show how much we've done and really emphasise that we've built up a community who will use and contribute to the Turing Way.

I've previously made posters in LaTeX, which is simultaneously satisfying and frustrating! But I don't think it'll be the right option here; Powerpoint (or similar) is easier to get a good design going with, especially if we have a template. Google slides might be worth a look because it'd be easier to collaborate on the content, but I've never used it for generating anything more than a basic deck of slides.

**Comment by pherterich** [comment] 2019-03-05 13:56
It's all over the place at the moment, but I'm trying to play around with something here: https://docs.google.com/presentation/d/1xXyVb8CBiYOUpLDnPsTV_NzZchOwcU1iMSpgeJTg_Do/edit?usp=sharing

**Comment by pherterich** [comment] 2019-03-05 15:06
@sgibson91 any preferences how you would like the BinderHub to be represented? Could we adapt your umbrella thing and replace GoogleCloud with Microsoft Azure and call it a Turing BinderHub with a few explaining bullet points? Happy to attempt this myself if that would be helpful.

**Comment by sgibson91** [comment] 2019-03-05 15:23
@pherterich Yes we could modify that - probably easier for me to do as I have the raw pptx. See also issue #246 which gives an overview on what we want it to look like (though I'm not 100% on Level 1, definitely 2 and 3 though).

**Comment by pherterich** [comment] 2019-03-05 15:37
@sgibson91 it says deadline is 19th, so worst case we could use the morning of the Sheffield sprint to finish everything and put it together. 
I'm just making a start to make sure we know which content to produce and we don't panic on the 19th.

**Comment by pherterich** [comment] 2019-03-05 15:59
@r-j-arnold happy to attempt a chapter flowchart, I couldn't find any prerequisites noted for the chapters CI, testing, and computing environments anywhere, could you point me to the right place then I can give it a go.

**Comment by r-j-arnold** [comment] 2019-03-05 16:34
@pherterich 

Testing chapter prerequisites: experience with the command line
Reproducible Environments chapter prerequisites:  experience with the command line, version control
CI chapter prerequisites:  experience with the command line, version control, testing, reproducible Environments

**Comment by pherterich** [comment] 2019-03-11 15:03
@r-j-arnold do we cover the command line somewhere or link out to some good reading (or ask people to attend software carpentry or something similar)? Going through my flowchart attempt, the command line seems to unlock everything and I'm not sure how we cover this.

**Comment by r-j-arnold** [comment] 2019-03-11 15:17
@pherterich I swear I linked to a resource on it in the relevant chapter's prerequisites, but it's not there so it's possible I just thought about doing it and never actually did. I'll make an issue about it and get around to it when I have a chance.

**Comment by pherterich** [comment] 2019-03-11 15:42
Thanks @r-j-arnold ! Not me going mad then. If I got everything correctly, our recommending readigng is this then:

![TuringWay_Chapters](https://user-images.githubusercontent.com/8457675/54136339-7f296f00-4413-11e9-83a2-307eefeca1fd.png)

Any comments welcome, I've just thrown it into Powerpoint to get a starting point.

**Comment by r-j-arnold** [comment] 2019-03-11 16:01
Hey @pherterich one minor tweak. Reproducible environments doesn't depend on testing, though CI does depend on both of then so that bit should look like

Testing-------------------------------|
                                                        | -------- CI
Reproducible environments--------|

**Comment by pherterich** [comment] 2019-03-11 16:13
Ahh, thanks @r-j-arnold - I misinterpreted my messy handwritten notes when digitizing them! New attempt:
![TuringWay_Chapters_v2](https://user-images.githubusercontent.com/8457675/54138955-6e2f2c80-4418-11e9-9686-97da717a00d2.png)

**Comment by r-j-arnold** [comment] 2019-03-11 16:30
Looks good @pherterich!

**Comment by pherterich** [comment] 2019-03-25 16:19
Closing this as poster is done and added here.

**Closed by pherterich** 2019-03-25 16:19 UTC
Labels: comms
