### ISSUE TITLE
Where should 'Credit for reproducible research sit?

### ISSUE THREAD

**Issue by FrancesMadden** [alan-turing-institute/the-turing-way#909] opened 2020-02-21 15:06 UTC
### Summary
Need to decide where the 'Credit for reproducible research' sit within the new structure of the book(s). 
There are several options including:
- reproducibility
- communication
- collaboration

There is some overlap between the content in this chapter and the Open Research, esp Open Data and Research Data Management chapters which was somewhat resolved by expanding the credit chapter during Feb20 dash. But the location of this information will need to be considered to be sure that adequate attention is given to it across the different sections of the book as the structure develops.  

### What needs to be done?

- [ ] Determine what info relates to 'data sharing' and what relates to 'credit'. 
- [ ] Determine what info needs to go where

### Who can help?

* [ ] Kirstie Whittaker
- [ ] Susanna? 

---

### Updates

N/A

**Comment by malvikasharan** [comment] 2020-02-25 14:19
Hi @FrancesMadden, At the moment this is a separate chapter as "Credit for reproducible research", so if you could contribute to that by creating subheading when needed (i.e. credit for different components such as data, method, project management etc.), it will make things clear. Do you other ideas on this?

**Comment by KirstieJane** [comment] 2020-02-25 15:03
Thanks @FrancesMadden! @malvikasharan - this was an issue I asked Frances to make because it isn’t clear which of the 5 new books “credit” sits in. I don’t think this issue has to close any time soon - it’s an important one to gather some input on and discuss 🌸

**Comment by malvikasharan** [comment] 2020-02-27 10:16
Got it @KirstieJane. @FrancesMadden please ignore my earlier comment.

My two cents: If we are talking about credit for reproducible research - that should be in the reproducibility book. For other books, there should be credit for the respective topics.

**Comment by EstherPlomp** [comment] 2020-03-04 15:47
I think that if we remove the part about citing/DOIs (Step 4) from the Open Data section in the chapter Open Research, there is less overlap with the credit chapter. Step 4 currently contains a lot of jargon that is not really applicable if you just want to archive your dataset somewhere, so I think that should be relatively easy adjusted.

From my viewpoint Open Data and RDM are also not that much overlapping in the sense that you can do data management without opening up your data. If we keep those topics separate, we could add some practical example of how to choose a repository in the open data bit and then just refer to the Open Data section in the RDM chapter.

As to the question where credit goes if there are new chapters... I'll have another think about that! I would like it if there is one overview of things you could receive credit for and how, but perhaps splitting them, like Malvika suggests, is a better idea if it is not big enough to be it's own thing compared to the other books.

**Comment by EstherPlomp** [comment] 2023-01-16 19:29
Hi all! Looking at some of the older issues as part of the review/editing group: 

I think this issue is resolved as we have the "[Making Research Objects Citable](https://the-turing-way.netlify.app/communication/citable.html)" chapter in the Communication book? 

@malvikasharan; what do you think?

**Comment by malvikasharan** [comment] 2023-01-16 19:38
I agree @EstherPlomp. This subchapter covers the content well: https://the-turing-way.netlify.app/communication/citable/citable-cite.html.
I will consider the issue resolved.

**Comment by EstherPlomp** [comment] 2023-01-16 20:16
Cool -Thanks! I'll close this issue for now then - otherwise it can always be reopened!

**Closed by EstherPlomp** 2023-01-16 20:16 UTC
Labels: help wanted, book-dash-feb20
