### ISSUE TITLE
Adding contributors details from the book dash | Biohackathon November 2020

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1584] opened 2020-11-13 09:50 UTC
### Summary

* We ran a book dash from 9-13 November 2020, and we would like to capture their highlights and work

### What needs to be done?

Please make sure that you share your feedback and experience from the last 5 days with us in this document: https://hackmd.io/@turingway/bookdash-nov2020-feedback-day5
1. Comment below with a link to your issues and PRs
2. Comment below your details in the following format (Kirstie's bio/details below for example):

```
* Role: Book Dash 2020 participant
* GitHub id: 
* ORCID: 
* Short bio:
>
* Personal highlights:
>
* More information:
>
```
```
### Kirstie Whitaker

* Role: **Project lead**
* GitHub id: [kirstiejane](http://github.com/kirstiejane)
* ORCID: [0000-0001-8498-4059](https://orcid.org/0000-0001-8498-4059)
* Short bio:
> I'm the lead of Tools, Practices and Systems research Programme at the Alan Turing Institute.
I have a PhD in Neuroscience from the University of California at Berkeley and conducted my postdoctoral research at the University of Cambridge in the Brain Mapping Unit.
I am a Mozilla fellowship (2016) and Fulbright scholarship (2007) alumna.

* Personal highlights:
> I am the lead of _The Turing Way_.
> I've done a lot of advocacy for changing research culture to make our work more efficient and effective, and I've noticed that we need to address the power structures in academia if we are to truly make research reproducible by default.
> I'm excited to build the Turing Way to both inspire the people who DO the research to make all their outputs as accessible as possible, and to nudge everyone else in the ecosystem to care about the work required to do so.

* More information:
> I'm really passionate about the concept of making science "open for all".
> I take that to mean we should share all of our outputs - the data, code and protocols that we develop - whether they're "significant" or not.
> But it also includes making those outputs FAIR - findable, accessible, interoperable and reusable. I am an advocate for greater diversity in STEM and in data science and particularly passionate about improving the ways we reward collaborative and supportive working.
> Finally, I'd like to pivot to having data science project be developed in the open from the beginning and with a decision making governance processs that is inclusive and community-lead.
```

### Who can help?

* All book dash attendees

---

### Updates

You can also add sections on:

* What skills/knowledge have you developed through *The Turing Way*
* What outreach have you undertaken for *The Turing Way* community
  * These could be blogs, talks, tutorials, trainings etc...
* Do you know of any data science research / practices that have changed and improved as a result of working on *The Turing Way*

If you can add a "quotes" section with a short quote that you're happy to be credited saying that would be so cool!

Please feel free to create sections as they make most sense.

**Comment by LauraCarter** [comment] 2020-11-13 10:20
```
* Role: [OLS project lead](https://github.com/alan-turing-institute/the-turing-way/tree/master/open-life-science-mentoring): Ethics Research Framework (2020)
* GitHub id: [Laura Carter](https://github.com/LauraCarter)
* ORCID: [0000-0002-4285-1140](https://orcid.org/0000-0002-4285-1140)
* Short bio:
> I'm a PhD candidate in the Human Rights Centre at the University of Essex, UK, researching the human rights implications of the use of data-driven technologies in the UK public sector, focusing on gender stereotyping and gender discrimination. Prior to my PhD, I worked as a human rights researcher for almost a decade, specialising mostly in human rights, sexual orientation and gender identity. I carried out field research in Europe and sub-Saharan Africa covering topics including homophobic and transphobic hate crimes, criminalisation of homosexuality and of sex work, legal gender recognition for trans people, and health rights for intersex people.

* Personal highlights:
> I'm excited to be part of an [OLS-2](https://openlifesci.org/) mentee cohort alongside [Ismael Kherroubi Garcia](https://github.com/Ismael-KG) and [Sophia Batchelor](https://github.com/BrainonSilicon), working on the _Guide to Ethical Research_: if you're interested in building a community of thoughtful, reflective, ethical data scientists, please come and join us!
> I was part of the November 2020 Book Dash: I worked on a chapter of the Ethics book on relating ethics to law, policy and human rights, and reviewed @irenekp's chapter on data anonymisation and @EKaroune's chapters on getting up and running on github. I also got to have lots of interesting conversations about ethics in data science: watch this space for more chapters!

* More information:
> I'm interested in feminist and queer research methodologies and in interrogating structures of power and systems of categorisation. Throughout my career, most of my work has been on understanding these systems, how they work, and how they harm: so that they can be dismantled!
> More information about me on my [website](https://lauracarter.github.io/).

* Quotes:
> "I'm not from a tech field but I've learned so much about github as a tool for collaborative working: thanks so much for everyone who was part of the November 2020 book dash for all your useful advice!"
```

**Comment by Ismael-KG** [comment] 2020-11-13 10:28
### Issue and PR

I have worked on this issue, clarifying its outline: https://github.com/alan-turing-institute/the-turing-way/issues/1235
I have finalised the intro to the Guide for Ethical Research, which is now ready for review: https://github.com/alan-turing-institute/the-turing-way/pull/1228
I also reviewed the Data Anonymisation chapter: https://github.com/alan-turing-institute/the-turing-way/pull/1579

### A quote!

>Research Ethics is complex, and two related concepts are Responsible Research and Innovation (RRI) and Research Integrity. Depending on whether we wear an RRI hat or research integrity goggles, we will encounter different research ethics questions. But it is important to wear the two at all times. I call this Steampunk Research Ethics.

### A blog post!

I will link this to the intro chapter once merged, but the ideas for the chapter are told and analysed at greater length here (includes links to TTW's code of conduct and to the Autistica Project): https://medium.com/@ismaelkherroubi/clarifying-ethical-research-fec39fc181

### Role: Core contributor, OLS project lead: The Turing Way's Guide for Ethical Research; Ethics Research Assistant at The Alan Turing Institute

GitHub id: Ismael-KG

Short bio:

I’m Ethics Research Assistant at the Alan Turing Institute. I have a BSc in Business Management and Administration and am currently working towards an MSc in Philosophy of the Social Sciences. I am also an associate member of the Chartered Institute of Personnel and Development (CIPD).

Personal highlights:

Since my undergraduate degree, I have worked in fintech and then in arts organisations within human resources teams, finally reaching the Alan Turing Institute and helping support the Ethics Advisory Group since April 2020. I think my highlight is that I’ve got a great background as a generalist! I am currently really thrilled to be working alongside Laura Carter and Sophia Batchelor to build a community around the Guide for Ethical Research! And I am proud to introduce the concept of Steampunk Ethical Research.

More information:

I am really fascinated by philosophical discussions about the social sciences, so I love the thought of questioning what an open science culture looks like and how to get there.

**Comment by irenekp** [comment] 2020-11-13 10:37
### Irene K

* GitHub id: [irenekp](http://github.com/irenekp)
* Short bio:
> I'm an undergraduate student majoring in Information Science and Engineering. While short, my journey with Data Science and Data Management has been varied and I've loved watching how a single concept can mould into so many different disciplines! I have been able to work with data science as an RA for a couple of projects that focused on different aspects of Social Network Analysis. I've also been able to follow data management and related practices during my internships at a fintech and a telecom company.

* Personal highlights:
> Turing Way was my first foray into Open Source, and I have found it extremely helpful in learning both about general github and open source practices as well as being part of a moving and collaborative community. I especially loved being part of an extremely multidisciplinary group of people, really shows me the real span of Data Science!
> The ethics book has been a great source of interest for me as it encompasses many of the issues I both grappled with, debated and deliberated upon extensively during my own data science projects. 
> During my time working on the Data Anonymization Chapter (Issue: #1578 , Pull Request: #1579 ) I managed to read more extensively about anonymization and I found answers to many of the questions that had previously bothered me.
> I really hope that the work we've done here to consolidate all these ethical guidelines will help make practicing data science with a strong ethical basis and clear moral conscience more easy and accessible.

* More information:
> In line with my contributions so far, I am extremely passionate about working on an ethical framework for Data Science, seeing as a lot of it focuses on exposing patterns that could easily be invasive, I really think an ethical approach to it is the only way to keep practicing it sustainably in the long term.
> Science Communication is an other one of my key areas of interest, I've been combining it with my love for sustainable practices (be it data science or water resource management) so far to research upon and write articles that I hope would inform and educate more people! I hope to add Data Visualization to this combination soon!
> I intend to keep working at the cross roads of Data Science and Sci-Comm for the foreseeable future!

**Comment by EKaroune** [comment] 2020-11-13 10:41
* Role: Contributor to Guide for Collaboration, **OLS2 project lead**: [Open Science in Phytolith Research](https://ekaroune.github.io/Open-Science-in-Phytolith-Research/).
* GitHub id: [EKaroune](https://github.com/EKaroune)
* ORCID: [0000-0002-6576-6053](https://orcid.org/0000-0002-6576-6053)
* Short bio:
I'm an independent post-doctoral researcher working in the field of Environmental Archaeology and Palaeoecology.  I have a PhD in Palaeoecology from the Institute of ArchaeoIogy, University College London. I am currently working on a project with Historic England concerning the development of novel methodologies in phytolith research for application to British Archaeological remains. I am also working on a project to improve the FAIRness of phytolith data.

* Personal highlights:
I have really enjoyed working in such a collaborative way during the bookdash. I have had interesting discussions concerning accessibility of The Turing way and research in general with other contributors. I have further developed my Github skills by working in collaboration with @paulowoicho, @malvikasharan and @KirstieJane to develop a chapter on 'getting started on Github'. This improvement in my skills will really benefit my own personal research to develop my own collaborative working groups and teach others how to use these research tools.
* More information:
I try to work as openly as possible and a large part of my current research is developing easy and accessible to all collaborative and open ways of working. I am also working hard to  bring together specialists in my field into a working group for Open Science so that we can  work collaboratively towards subject-specific FAIR guidelines for phytolith data.

**Comment by Marta-MM** [comment] 2020-11-13 10:44
Link to issues and PR:
- #1539, #1556, #1568, #1569, #1570: checked for typos/formatting, proofread
- #1563: proposed a chapter on data visualisation
- #1572 proposed a section on cognitive biases/constraints in visualising and understanding data
- #1585: proposed a pre-registration section for the reproducibility book

* Role: **contributor**
* GitHub id: [Marta-MM](http://github.com/Marta-MM)
* ORCID: [0000-0001-7995-3717](https://orcid.org/0000-0001-7995-3717)

* Short bio: 
I am a Research Assistant in the JDM lab at the University of Leicester. At UoL, I am also social media officer for the Post Doc and Research Staff association and ECR representative for my department. I hold an MSc in Social Psychology and a Ph.D. in Cognitive and Brain Sciences and my main research interests involve decision making, social hypothesis testing, and reasoning biases.
>
* Personal highlights:
In the **November 2020 book dash**, I used GitHub for the first time! I helped fix some small bugs (grammar and syntax, typos, formatting) and, I proposed two chapters on data visualisation and on study pre-registration.
>
* More information:
I am passionate about science communication and research dissemination and interested in replicability, open science issues, and the interface between cognitive and social aspects in social psychology topics like intergroup relations and impression formation. At the moment I am particularly fascinated by data visualisation and infographics.

* Skills I have developed through The Turing Way:
I started familiarising myself with the GitHub environment and learned how to collaborate through it to provide valuable contributions to the project. My work during these 5 days has mostly been individual, but I would really love to collaborate with others to work on the two chapters I suggested!

**Comment by jmfernandez** [comment] 2020-11-13 11:27
Link to revised PR:

* #912: checked for typos.

* #1320: checked for typos, made some suggestions (which were accepted).

Additional details
* Role: **contributor**

* GitHub id: @jmfernandez

* ORCID: [0000-0002-4806-5140](https://orcid.org/0000-0002-4806-5140).

* Short bio:
  I'm a senior research engineer from [INB](https://inb-elixir.es) coordination unit, [BSC](https://bsc.es), ELIXIR Spain. With a MSc in Computer Science, I have been working in bioinformatics since 1999, involved in very disparate projects along these years. Currently I'm very involved into technical and scientific benchmarking, reproducibility and workflow execution abstractions, among other topics.

* Personal highlights:
  I have really enjoyed meeting so warming and dynamic community around The Turing Way!

**Comment by lauracion** [comment] 2020-11-13 12:13
* Some of my contributions this week can be found on these PRs: #1553, #1507, reviewed [this translation](https://docs.google.com/presentation/d/1N1mYNlvBTdGBfqVoKDmDxtXgpMuwuFIW/edit#slide=id.p1) generated by [Marilina Santero](https://twitter.com/SanteroMarilina), and worked with [Jem](https://twitter.com/jmiltondraws) to create new cartoons for The Turing Way. Plus a great of valuable networking. 
* Role: Researcher in Health Data Science
* GitHub id: [lauracion](http://github.com/lauracion)
* ORCID: [0000-0001-5213-6012](https://orcid.org/0000-0001-5213-6012)
* Short bio: 
I am a Biostatistician who transitioned to Data Science. I work at the University of Buenos Aires (Argentina). I specialize in several areas of Health Sciences. I am passionate about changing the way applied stats is taught and practiced. I have so much to learn and do; it seems I will need extra lives to accomplish all. More about me [here](https://lacion.rbind.io).
* Personal highlights:
I hope this is my first of several Book Dashes! It was an outstanding experience. Thank you so much, Malvika and Kirstie, for brilliantly organizing and coordinating this event! ✨ 💖

**Comment by BatoolMM** [comment] 2020-11-13 16:17
* Contributions : 
    * **CI service chapter:**
        * [PR #1551: Maintaining consistency in CI chapter.](https://github.com/alan-turing-institute/the-turing-way/pull/1551)
        * [issue #1557: Adding a new sub-chapter for GitHub actions](https://github.com/alan-turing-institute/the-turing-way/issues/1557)
        * [PR #1588: A new sub-chapter for GitHub actions](https://github.com/alan-turing-institute/the-turing-way/pull/1588)
There is still lots of work to be done in this chapter but hopefully, I can finish it off this weekend.
    * **Layout:**
        * [PR #1561: Enabling collaborative annotation in the book.](https://github.com/alan-turing-institute/the-turing-way/pull/1561)
    *  **Translation**
        *  [PR #1586: Translate README.md to Arabic](https://github.com/alan-turing-institute/the-turing-way/pull/1586)
* Role: Researcher at the University of Liverpool.
* ORCID: 0000-0002-3905-2751
* Short bio: I'm the founder of R-Ladies in Saudi Arabia (Dammam). I initially majored in pharmacology but quickly developed an interest in biochemistry, structural biology, and bioinformatics. I enjoy applying deep learning to answer biological questions. 
* Personal highlights: I find it hard to express my personal thoughts and feelings in words. This was such an amazing experience. It helped me to develop my technical skills. Thank you so much to everyone I met in this Book Dash event :heart:.

**Comment by ashatitus** [comment] 2020-11-13 18:04
* Role: Data Ethics Researcher at the LSE
* GitHub id: [ashatitus](http://github.com/ashatitus)
* ORCID: [To create ORCID number] (https://www.lse.ac.uk/media-and-communications/people/research-staff/asha-titus)
* Contributions: 
- Provided case study template (and reading material on good case study design) from previous research to @paulowoicho 
- Worked with Jem to create a really great 'Robodebt' illustration that shows the human impact of large scale data science projects! Drawing on the implementation experience of the Australian federal government's Online Compliance Initiative (that will be written up in the case study section #1238), Jem worked up a fantastic caricature of how this kind of data science project criminalizes those on welfare and disability benefit.
- Proposed sub chapter on data literacy issues and touching on using legal processes to develop capacities to understand and intervene around large scale data infrastructures. WIP #1582 
- Listened to ethics guide ideas from @Ismael-KG @LauraCarter @BrainonSilicon and suggested case studies of data science in use in government - pointing out content and examples of biases in algorithmic design from Aus and UK government large scale data driven projects (watch this space! #1238)
* Short bio:
>
* Personal highlights:
>
* More information:

**Comment by SamGuay** [comment] 2020-11-14 18:22
* Role: Contributor
* GitHub id: [SamGuay](https://github.com/SamGuay)
* ORCID: [0000-0001-6990-839X](https://orcid.org/0000-0001-6990-839X)
* Short bio:
> I'm a PhD student in Cognitive Neuroscience at the University of Montreal, Canada, researching the effects of repetitve head impacts in active and retired athletes with a neuroimaging perspective. In parallel, I've started the [Open Science UMontreal](https://umontreal.openscience.ca) initiative to equip early-career scientists with better knowledge and tools to implement more open science in their workflow. The OSUM community members are really awesome :rocket:.
* Personal highlight:
> The whole November 2020 Book Dash was my highlight. I got to know a welcoming community and amazing humans throughout the week. It was amazing to witness so much progress in that tiny amount of time.

Issues and PRs I've worked on
*    #1593 - Improving accessibility by enabling a dark theme.
*   Read a bunch of contents related to #1343 and #1342
*   Reviewed #1346 and #1339.
*   Have started to review @LauraCarter's PR #1394.
*   Suggested [hypothes.is](https://hypothes.is) when people were looking for highlighting tools. Then people did magic in seconds and #1561 was open!

**Comment by kderuyck** [comment] 2020-11-17 10:26
* Contributions :
           #1562: adding a new sub-chapter on Research Data Management Toolkits
           #1553, #1559: reading the content of these chapters

* Role: contributor, from the side of the ELIXIR BioHackathon

* GitHub id: kderuyck

* ORCID: 0000-0001-9921-644X

* Short bio: Since 2016, I am managing the Belgium ELIXIR Node (we pursue FAIRification of research data and facilitating reproducible analysis, through activities in data management and analysis as well as training; we also focus on domain specific services in plant sciences, human health and proteomics). I was trained as a Bioscience engineer, have a PhD in Medical Sciences and performed medical genetics research for many years. 

* Personal highlights: I started familiarizing myself with the GitHub environment and learned how to collaborate through it. It was especially nice to meet the vibrant community working together on the Turing Way!

**Comment by malvikasharan** [comment] 2020-11-19 19:20
@all-contributors please add @BatoolMM for idea, content, translation and infrastructure

**Comment by malvikasharan** [comment] 2020-11-19 19:22
@SamGuay @kderuyck @jmfernandez @EKaroune @Ismael-KG and @LauraCarter have already been added to the contributor's table.

**Comment by malvikasharan** [comment] 2020-11-19 19:24
@all-contributors please add @lauracion for content

**Comment by malvikasharan** [comment] 2020-11-19 19:28
@all-contributors please add @irenekp for content

**Comment by malvikasharan** [comment] 2020-11-19 19:48
Need to add @vcheplygina, @bsipocz, @luucamay, @msanter01, @c-martinez, @sk-sahu, @martinagvilas and @sgibson91 contributions.

**Comment by martinagvilas** [comment] 2020-11-20 20:25
**Contributions at the Book Dash 2020**
- Worked with @BatoolMM on the upgrade of the Jupyter Book that allows for annotation (PR #1516)
- Explored ways of printing a single pdf for the whole book (failed so far), generate a general table of contents (failed so far), and looked into redirects with sphinx (issue #1542)
- Some mentoring _(in spanish as well 🇦🇷 🇧🇴 )_
- I also gave a talk about The Turing Way and computational reproducibility at the [Brainhack Donostia 2020](https://brainhack-donostia.github.io/) (slides [here](https://zenodo.org/record/4269795#.X7glTlNKitg))
---
**Personal information**
* Role: Book Dash 2020 participant and Core Contributor/Mantainer of The Turing Way
* GitHub id: @martinagvilas 
* ORCID: https://orcid.org/0000-0002-1097-8534
* Short bio:
> I'm currently finishing my PhD in Neuroscience at the Max-Planck-Institute AE in Frankfurt, Germany. I study how the brain processes conceptual knowledge analyzing neural recordings with computational modelling techniques. As an advocate of open-research, I also work on improving the reproducibility of neuroscientific-analyses and enjoy contributing to open-source software projects.
* Personal highlights:
> Since the Book Dash in February 2020, I help with the maintenance of The Turing Way infrastructure and its reliance on Jupyter Book. The Turing Way is not only a great guide for conducting reproducible research, but it also provides a wonderful entry point into open-source contribution in general and connects you to a variety of open data-science communities. I'm also a mentor at the OLS-2 program and I have also worked with the pandas core-contributors in providing guidance to people from underrepresented groups in technology on making their first open-source contribution.
* More information:
>More information about me can be read on my website.

**Comment by paulowoicho** [comment] 2020-12-02 12:34
**Contributions at the Book Dash 2020**
- 

* Role: Book Dash 2020 participant, Google Season of Docs Participant/Technical Writer on _The Turing Way_
* GitHub id: @paulowoicho
* Short bio:
> I just completed a Master's in Data Science from the University of Glasgow and will be starting a PhD in January 2021 where I will be studying coversational information-seeking systems. Currently, I am participating in the Google Season of Docs program as a technical writer.

* Personal highlights:
>
* More information:
>

**Comment by malvikasharan** [comment] 2020-12-07 13:28
@all-contributors please add @msanter01 for translation and presentation https://twitter.com/turingway/status/1335914239962329088?s=20

**Comment by malvikasharan** [comment] 2020-12-07 13:30
@all-contributors please add @msanter01 for translation and talks https://twitter.com/turingway/status/1335914239962329088?s=20

**Comment by malvikasharan** [comment] 2020-12-07 13:37
@all-contributors please add @luucamay for review

**Comment by malvikasharan** [comment] 2020-12-07 13:45
@all-contributors please add @sk-sahu for ideas

**Comment by malvikasharan** [comment] 2020-12-09 18:00
Adding comments to contributors.md file in PR #1688.

**Closed** 2021-02-26 09:10 UTC
Labels: book-dash-nov20, community
