### ISSUE TITLE
[BUG] Cannot build the book locally

### ISSUE THREAD

**Issue by chadsgilbert** [alan-turing-institute/the-turing-way#1187] opened 2020-06-01 23:52 UTC
### Bug description

I cannot build the book locally to look at changes before submitting them.

#### Expected behaviour

I think it should be easy to reproduce this book on my own machine by cloning and running the scripts given in `CONTRIBUTING.md` in the *Local Development* section. This does not work on my machine.

### How to reproduce

Following this step from CONTIBUTING:
```
pip install -r requirements.txt
```
gives me an error:
```
ERROR: No matching distribution found for jupyter-book>=0.7.0b. (from -r book/website/requirements.txt (line 8))
```

### Your personal set up

- OS: Fedora 31
- Multiple python projects in various virtualenvs

**Comment by malvikasharan** [comment] 2020-06-02 08:27
Hi @chadsgilbert, you need to make sure that your do these two things:

1) upgrade your jupyterbook locally. 

2) use Python 3 and pip3 explicitly if they are not your default.

**Comment by chadsgilbert** [comment] 2020-06-02 20:39
Thanks for your help @malvikasharan.

I've tried again using python 3.7 form my system and this time I ran inside a fresh `virtualenv` in case there is something on my system that is causing a conflict. At this point, I still can't complete the installation.

```
Looking in indexes: https://pypi.python.org/pypi/
Collecting pandas
  Using cached pandas-1.0.4-cp37-cp37m-manylinux1_x86_64.whl (10.1 MB)
Collecting numpy
  Using cached numpy-1.18.4-cp37-cp37m-manylinux1_x86_64.whl (20.2 MB)
Processing /home/chad/.cache/pip/wheels/19/76/ab/0a1b5233d7d0f1c961d6698488a20018e977837feadc25e6cb/datascience-0.15.4-py3-none-any.whl
Collecting folium
  Using cached folium-0.11.0-py2.py3-none-any.whl (93 kB)
Collecting matplotlib
  Using cached matplotlib-3.2.1-cp37-cp37m-manylinux1_x86_64.whl (12.4 MB)
ERROR: Could not find a version that satisfies the requirement jupyter-book>=0.7.0b. (from -r book/website/requirements.txt (line 8)) (from versions: 0.6.5)
ERROR: No matching distribution found for jupyter-book>=0.7.0b. (from -r book/website/requirements.txt (line 8))
```

I can't see what's different from the Ubuntu container image that I defined, but do far I can get one to work and not the other. I'll keep poking a bit. I am not very familiar with `pip`.

**Comment by chadsgilbert** [comment] 2020-06-02 20:48
Looking [here](https://pypi.org/project/jupyter-book/#history) I can see that the 0.7.0 releases of jupyter-book are still flagged as `pre-release`. I wonder if that's causing the problem. I can't resolve it with the `--pre` flag, unfortunately.

**Comment by malvikasharan** [comment] 2020-06-02 20:53
I have been using it locally without any issue. One thing that worked for me was to completely uninstall jupyterbook from my system and reinstall with pip3. Can you please try that?

**Comment by kkmann** [comment] 2020-07-08 07:58
Hm, I agree that the documentation for actually building the book has gotten burried a bit in all the other important contributing guidelines. 

For the concrete problem, I would advise using the virtual environment approach (general piece of advice: use your system level python as little as possible). Strangely enough, the approach itself is not documented in the chapter on reproducible environments. We only cover conda at the moment.

**Comment by varlottaang** [comment] 2020-09-22 13:31
I had the same issue trying to build the book locally with    
`pip install -r book/website/requirements.txt`
error 
`pip: command not found`
 **pip3** worked fine (python 3.8 on mac)
`pip3 install -r book/website/requirements.txt`

**Comment by aleesteele** [comment] 2022-10-31 11:24
Perhaps connected to #2611?

**Comment by da5nsy** [comment] 2022-11-05 05:04
> Perhaps connected to #2611?

Shouldn't be.
It looks like the first comments on this issue were to do with the availability of a specific version of Jupyter Notebook at the time, and [the later comment](https://github.com/alan-turing-institute/the-turing-way/issues/1187#issuecomment-696723543) was a specific issue relating to pip/pip3.

Considering that the latest comment on this issue was 2 years ago, I shall close this issue. If there are any current issues with local building please open a new issue.

**Closed by da5nsy** 2022-11-05 05:04 UTC
Labels: bug
