### ISSUE TITLE
Reorganise chapters into subsections

### ISSUE THREAD

**Issue by rainsworth** [alan-turing-institute/the-turing-way#468] opened 2019-05-16 13:14 UTC
### Summary

Currently, most of the chapters are one long page. We would like each chapter to be restructured into subsections like the chapter on [Reproducibility](https://the-turing-way.netlify.com/reproducibility/reproducibility.html) which was done in this pull request:
https://github.com/alan-turing-institute/the-turing-way-book/pull/12 

(*Note that we are no longer using a separate GitHub repository for the book, sorry for any confusion linking to a different repo pull request here!)

### What needs to be done?

- [x] Restructure Open Research chapter
   - [x] Update the [Table of Contents](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/_data/toc.yml)
- [x] Restructure Version Control chapter
   - [x] Update the [Table of Contents](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/_data/toc.yml)
- [x] Restructure Collaborating on GitHub/GitLab chapter
   - [x] Update the [Table of Contents](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/_data/toc.yml)
- [x] Restructure Research Data Management chapter
   - [x] Update the [Table of Contents](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/_data/toc.yml)
- [x] Restructure Reproducible Environments chapter
   - [x] Update the [Table of Contents](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/_data/toc.yml)
- [x] Restructure Testing chapter
   - [x] Update the [Table of Contents](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/_data/toc.yml)
- [x] Restructure Reviewing chapter
   - [x] Update the [Table of Contents](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/_data/toc.yml)
- [x] Restructure Continuous Integration chapter
   - [x] Update the [Table of Contents](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/_data/toc.yml)
- [x] Restructure Reproducible Research with Make chapter
   - [x] Update the [Table of Contents](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/_data/toc.yml)
- [x] Restructure Risk Assessment chapter
   - [x] Update the [Table of Contents](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/_data/toc.yml)

### Who can help?

* Anyone who wants to test out their GitHub skills! :) You can see how it was done previously in  this pull request: https://github.com/alan-turing-institute/the-turing-way-book/pull/12

---

**Comment by jspickering** [comment] 2019-05-17 08:32
I'm going to try and restructure the Open Research chapter - my first pull request incoming in...some short time in the future :)

**Comment by rainsworth** [comment] 2019-05-17 10:18
Thank you so much @jspickering! 👏  Would you be able to update the [Table of Contents](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/_data/toc.yml) to reflect the new sections? If you've moved on to something else @pherterich or I could take a crack at it :)

**Comment by jspickering** [comment] 2019-05-17 11:02
I've edited the [Table of Contents](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/_data/toc.yml) file!

**Comment by rosiehigman** [comment] 2019-05-17 11:40
I'm going to have a go at restructuring the Risk Assessment chapter

**Comment by jspickering** [comment] 2019-05-17 14:33
I'll restructure the Version Control chapter

**Comment by cassgvp** [comment] 2019-05-28 09:04
> I'll restructure the Version Control chapter
> 
> Edit: I will leave this for someone at the London book dash! :)

 - I'll pick this up! 💃

**Comment by rosiehigman** [comment] 2019-05-28 09:58
I'll pick up the Collaborating with GitHub/GitLab chapter

**Comment by masonlr** [comment] 2019-05-28 10:22
I'll pick up the Reproducible Environments chapter with PR https://github.com/alan-turing-institute/the-turing-way/pull/575

**Comment by masonlr** [comment] 2019-05-28 10:53
Please note:

1. Each PR will need to update `website/_data/toc.yaml`

2. Any table-of-contents markdown content will need to be edited to reference external files: for example if you had a reference to content in the current file

    ```
    - [Binder](#Binder_section)
    ```
    
    and then moved to a new file `./04/binder.md`, you'll need to update the link to
    
    ```
    - [Binder](./04/binder#Binder_section)
    ```

**Comment by rainsworth** [comment] 2019-05-28 10:55
> Please note:
> 
>     1. Each PR will need to update `website/_data/toc.yaml`
> 
>     2. Any table-of-contents markdown content will need to be edited to reference external files: for example if you had a reference to content in the current file
>        ```
>        - [Binder](#Binder_section)
>        ```
>        
>        
>        and then moved to a new file `./04/binder.md`, you'll need to update the link to
>        ```
>        - [Binder](./04/binder#Binder_section)
>        ```

Thank you @masonlr, I'll get these instructions added to the Contributing Guidelines!

**Comment by masonlr** [comment] 2019-05-28 11:34
@rainsworth can we decide whether manual TOC entries are still needed in the book: see a new issue here https://github.com/alan-turing-institute/the-turing-way/issues/581

**Comment by rosiehigman** [comment] 2019-05-28 12:06
I'll take the Reviewing chapter, will remove the manual TOC as per @masonlr suggestion in #581

**Comment by rosiehigman** [comment] 2019-05-28 14:19
I'll take the Testing chapter

**Comment by christopherlovell** [comment] 2019-10-24 16:01
I can reorganise the version control chapter if no one else is doing this?

**Comment by masonlr** [comment] 2019-10-24 16:05
@christopherlovell go for it.

**Comment by KirstieJane** [comment] 2019-10-24 16:10
Thank you @christopherlovell!

**Comment by christopherlovell** [comment] 2019-10-25 17:32
pull request submitted #729 

(and my bad spelling fixed...)

**Comment by dblana** [comment] 2019-11-20 19:43
I will attempt to restructure the Research Data Management chapter...

**Comment by malvikasharan** [comment] 2020-04-14 11:40
Thank you for working on these chapters. Many of these changes have been accepted to the current version, thanks to many of you. ❤️️

Please see #977 for the chapters with subsections. I will keep this issue open till we get the PR merged.

**Comment by dingaaling** [comment] 2022-10-31 11:40
Hello from 2022! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. This issue looks like it has now been incorporated in the Turing Way in some way - https://github.com/alan-turing-institute/the-turing-way/pull/977 - or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!

**Closed by dingaaling** 2022-10-31 11:40 UTC
Labels: good first issue, reproducibility-book, book-dash-mcr2019
