### ISSUE TITLE
Blog post about Binder workshop

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#321] opened 2019-03-13 18:17 UTC
### Summary

I would LOVE for us to capture the participant experience at the [Boost your research reproducibility with Binder](https://github.com/alan-turing-institute/the-turing-way/tree/master/workshops/boost-research-reproducibility-binder) workshops.

My suggestion would be to have "workshop reports" that are written like blog posts. They could be saved in the [`workshops/boost-research-reproducibility-binder`](https://github.com/alan-turing-institute/the-turing-way/tree/master/workshops/boost-research-reproducibility-binder) folder and once we have them we can ship them out to other blogs that might want to feature them ✨ 

I think a report that was around 500-750 words long would be amazing.

### What needs to be done?

- [x] Ask the workshop participants if they would like to write a little report (and point them to this issue)
*Update:* Email sent on 27 March 2019
- [ ] Support them in preparing and submitting a PR with their report.

### Who can help?

* Any workshop participant! 💖 
* Any member of the team who wants to help support a new contributor 🤗 

---

### Updates

*No current updates*

**Comment by pherterich** [comment] 2019-03-19 10:36
@rosiehigman are you happy to take this on or shall I send this out through eventbrite at some point next week? We just said we will open a call and then shop around for a blog outlet hoping that the SSI will offer us a last resort.

**Comment by rosiehigman** [comment] 2019-03-20 20:19
I happy to do this, but it probably won't be until the end of next week so if you've got time to do it sooner go for it 😄

**Comment by pherterich** [comment] 2019-03-25 16:50
Draft email below, please comment/rewrite by Wednesday lunch time and I'll send it out Wednesday afternoon:

Dear “Boost your research reproducibility with Binder” participant,

Many thanks for joining our workshop. 

We would love to capture the amazing atmosphere in the room in a short workshop report and are looking for (a) volunteer(s) to write up their experience attending in a short blogpost (500 – 750 words). 

If you would like to contribute, please comment on [this issue](https://github.com/alan-turing-institute/the-turing-way/issues/321) on our GitHub repository or send us an email at theturingway@gmail.com and a team member will help with your contribution.

Note that we will not contact you via Eventbrite from now on, so if you want to keep up to date with the Turing Way, please sign up to our newsletter: https://tinyletter.com/TuringWay

Many thanks and best wishes,
The Turing Way team

**Comment by KirstieJane** [comment] 2019-03-27 14:54
Looks great to me! Thank you! 🚀

**Comment by sgibson91** [comment] 2019-03-27 14:55
> We would love to capture the amazing atmosphere in the room in a short workshop report and are looking for (a) volunteer(s) to write up their experience attending in a short blogpost (500 – 750 words).

I would remove the `(a)` here unless there's a hidden `(b)` to follow it up with. Otherwise it looks great!

**Comment by pherterich** [comment] 2019-03-27 14:57
@sgibson91 it's my attempt to capture a volunteer/volunteers all in one and made sense when I wrote it but I agree it's confusing now!

**Comment by sgibson91** [comment] 2019-03-27 15:00
Oh I see it now! Gotcha. Since you're using "their" later on in the sentence, I'd go with the plural 🙂

**Comment by pherterich** [comment] 2019-05-23 16:28
no one ever got back to us on that - should we just close this?

**Comment by harisood** [comment] 2022-10-24 10:41
Hello from autumn 2022 @KirstieJane and @pherterich! Hope all is well with you, many months later. The TTW Core team is following up on issues in our backlog and wanted to check if we now should close this issue? If so, feel free to comment or 👍  this comment. If not, please leave a comment on how we could revive this thread and how we can support this work.

We'll leave the issue open for now, and if we don't hear from you by mid-November we'll mark it as closed - but we are always happy to reopen it! Thank you!

**Comment by dingaaling** [comment] 2022-10-31 11:16
Hello from October 2022! The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!

**Closed by dingaaling** 2022-10-31 11:16 UTC
Labels: community, comms
