### ISSUE TITLE
[BUG]: [etoc] missing index.html written as redirect to 'welcome.html

### ISSUE THREAD

**Issue by sandygudie** [alan-turing-institute/the-turing-way#2986] opened 2023-03-02 18:48 UTC
### Description
Working on the translation chapter for the TTW book on PR https://github.com/alan-turing-institute/the-turing-way/pull/2961 and we have this bug in the build which reports `"[etoc] missing index.html written as redirect to 'welcome.html". `

The build works locally but fails in the Pull Request. 

### Failure Logs
![image](https://user-images.githubusercontent.com/54219127/222522285-b514d4d0-4249-4314-b1e2-eaeeb845a6e0.png)

**Comment by sandygudie** [comment] 2023-03-02 18:50
I came across this issue https://github.com/alan-turing-institute/the-turing-way/issues/2887, not sure how it was resolved.
@JimMadge  @BatoolMM @RealRichi3

**Comment by JimMadge** [comment] 2023-03-03 09:32
Hi.

I wrote what I think is going on [here](https://github.com/alan-turing-institute/the-turing-way/issues/2887#issuecomment-1413739068). In short, there is no `index.md` to convert to `index.html`. However, jupyterbook expects an `index.html` so it copies `welcome.html` to `index.html`.

That said, I think that is only a warning and shouldn't make the build fail. So maybe there is another problem?

**Comment by da5nsy** [comment] 2023-03-09 08:16
Closing as a duplicate of #2887

**Closed by da5nsy** 2023-03-09 08:16 UTC
Labels: bug, infrastructure
